# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atr',
            fields=[
                ('a_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=26)),
                ('title', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=26)),
                ('b_id', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Bks',
            fields=[
                ('b_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=26)),
                ('desc', models.CharField(max_length=400)),
                ('type', models.CharField(max_length=20)),
                ('edition', models.CharField(max_length=8)),
                ('p_year', models.IntegerField()),
                ('pub', models.CharField(max_length=50)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Atr')),
            ],
        ),
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bks')),
            ],
        ),
        migrations.CreateModel(
            name='Bowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateField()),
                ('issue', models.DateField()),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Bks')),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=50)),
                ('dpt_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Invt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.CharField(max_length=10)),
                ('rack', models.CharField(max_length=5)),
                ('row', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('i_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Bks')),
            ],
        ),
        migrations.CreateModel(
            name='Libmem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Librn',
            fields=[
                ('lb_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=26)),
                ('d_typ', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=250)),
                ('dpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(max_length=9)),
                ('stu_name', models.CharField(max_length=26)),
                ('d_typ', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=26)),
                ('address', models.CharField(max_length=250)),
                ('dpt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dept')),
                ('stu_id', models.OneToOneField(max_length=9, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City', models.CharField(default='NA', max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='libmem',
            name='cwid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Stud'),
        ),
        migrations.AddField(
            model_name='libmem',
            name='dpt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dept'),
        ),
        migrations.AddField(
            model_name='bowed',
            name='cwid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Libmem'),
        ),
        migrations.AddField(
            model_name='bowed',
            name='i_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Invt'),
        ),
        migrations.AddField(
            model_name='border',
            name='cwid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Libmem'),
        ),
        migrations.AddField(
            model_name='border',
            name='i_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Invt'),
        ),
        migrations.AddField(
            model_name='border',
            name='lb_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Librn'),
        ),
        migrations.AddField(
            model_name='bks',
            name='dpt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dept'),
        ),
    ]
