# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stud',
            name='id',
        ),
        migrations.AlterField(
            model_name='dept',
            name='dpt_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stud',
            name='stu_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
