# Generated by Django 2.0.7 on 2018-11-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181113_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atr',
            name='b_id',
        ),
    ]
